# Generated by Django 3.0.7 on 2020-06-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='sobre',
            new_name='sobrenome',
        ),
    ]
